export interface SimplifyOffer {
    id: any,
    floors_count: any,
    floor: any,
    total_area: any,
    rooms_count: any,
    price: any,
    latitude: any,
    longitude: any,
    metro: any,
    metro_time: any,
    metro_type: any,
    description: any,
    address: any,
    date: any,
    download_date: number,
}
